language: node_js
node_js:
- 12
- 10
before_install:
- echo "Ready to install!"


branches:
  only:
  - master

cache:
  directories:
  - node_modules

before_deploy:
  - npx typedoc --out ./documentation/ src --exclude "**/*+(test|index).tsx" --allowJs

deploy:

  - provider: npm
    email: juandara2222@gmail.com
    api_key:
      secure: VM1kopn72webVf0gHP6B1kvf8I1H2TU5q//BCyi817cB0lc+u78SPTfVtJSkjgUl8A5N1CLz8ORC4ZLH71BFsc+pIgxPUkJqP04UOkhO+BlckDjkNGGmOIvs5zJlonnmZ02/OUAOjiQSbTliqS8SRkSObV2inRSTCMhO9DjohBnrxeLmRvDCNYV6N3r7xiV7BsJ8KumcE/ML4sfStN9WpUTBPinjaM//t9kBm4RZCud6Tkl1sjz/ckpo1nsTRLZeuM7rbs0b3dc3xE8u2IQdFnAnu7z0JY/5HdZlL27rFnaqq0z5Ds7Wc1Yn0nKmBcunmeLoDIHZvnQ8v7fFn84yuFdnoMLeQ/FsHwgCtFVnbsGpLmW9x6IkopFPKsJ0r7zgu4+QcOwlEzX9xyuIssi5U+Zbc7Fh/Q9aNw/i/kA6vt5olzcF55L35K3fu9eNPYpOGHQ4KgmtLXRlhy2pUPlrDwDyrFw5cLx4RjOLY22Wp80dv2/dNC2ungD3ImmcE5jLu1KENXOJ780QvVjO1WPpxWagqjEttITb/IsBWwG0mcDLgVvRGzVhdQHWGpoSmoT4EDAbI+3MszFtdD5iRpwrz6y+ZqMxcXgC3L57HfMpRBvER3w2TH0JqF7khA0DA5lLO0Nxxhokju+EvbdQn3V0LI/p2y/HRAfUzE3PpMGnAj4=
    on:
      tags: true
      repo: juanda2222/vissually
    skip_cleanup: 'true'

  - provider: s3
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key:
      secure: "BDJ26DPgx1tGj336XbA3lsCeOllvvTvqI7JrSvdoy/zxbxfUKNX7D5Kqek/6LnmXwffJ3j5GJB6Ib2ROFpZJINLRyO2ceEqT9V/uHpnVx5x1g+NLcUbFPSIISuN3K/88fNeDfJgjREMmwMzBfJCvZxYS7RLAWZSYi94a2091BrjhCn56fDd6i+pwfuEn+UP53gftxv892I0rA+2t126OCk2rqilQ+9SOeQP+JJ7UZqkjQ25mehBZB46dYTfoG++5S/OooruIExuJjsy/CA/PhYu+TTFMqITL+cgxJpQGnY7rnDjHB79CCuhHBB4OBTlYxMvG/bYI8dZujwEw8y5skbOqBrSI8Z2CQ2cNMdWG01FC8PEFigpSfSj5XbtZDzkzw+qGvrCiYOuEBI1yZHASYmFA2CY2sQhn12Y/uiGu0mxjG8V2zjM8rFeIqmXhENfU9CyMMyK403uCofZt6J9XwLD6gj+UJgUqRlYe7PUbeCRzUw4u1vb6Rw38WPxhi+b+TfHsAuLyf24YCMpGfyRo8yqLzuZ6Hq9eDxs/ViaN99oclGi9cPk6FRuB8YiyfRg+tClHVq+lLMWJqjMfRveXF310jvK8Ef8D8OLwaGRF/6vwCwvf6H2sGdbphbf4j+M528dsVMgKFvpQogGBrPudU3+1unsopZQoRTAlJmBixs0="
    bucket: personal-public-files-23rde2
    local-dir: documentation
    acl: public_read
    on:
      repo: juanda2222/vissually
    skip_cleanup: 'true'
