language: node_js
node_js:
- 12
- 10
before_install:
- echo "Ready to install!"

branches:
  only:
  - master
  - /^v.*$/  # allow tag commits

cache:
  directories:
  - node_modules

before_deploy:
  - npx typedoc --out ./documentation/ src --exclude "**/*+(test|index).tsx" --allowJs

deploy:

  - provider: npm
    email: juandara2222@gmail.com
    api_key: "$NPM_API_KEY"
    on:
      tags: true
      all_branches: true
      repo: juanda2222/vissually
    skip_cleanup: 'true'

  - provider: s3
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_ACCESS_KEY"
    bucket: personal-public-files-23rde2
    local-dir: documentation
    acl: public_read
    on:
      repo: juanda2222/vissually
    skip_cleanup: 'true'

